### ISSUE TITLE
Problem on zigbbe2mqtt version 1.36.1

### ISSUE THREAD

**Issue by EskildPa** [somlioy/amina_s#1]
Thanks for publishing this, it has really been a great help.
Cannot get this to work with zigbee2mqtt version 1.36.1. Nothing in the log, no errors as far as I can see.
Downgraded to 1.36.0, and it works as before.

**Comment by somlioy** [comment]
There seems to be a breaking change on some "legacy requirements" in version 1.36.1.(https://github.com/Koenkk/zigbee2mqtt/issues/22083).

I tried the fix in (https://github.com/Koenkk/zigbee2mqtt/issues/22083#issuecomment-2037342969) and the convert then loads again, but there is another issue with configuration aswell. Everything except the amina cluster (65255, ev-status, alarms, kwh etc.) seems to be working.

Related issues regarding configuring:  
https://github.com/Koenkk/zigbee2mqtt/issues/22194
https://github.com/Koenkk/zigbee2mqtt/issues/22172

Added the change in the dev branch (https://github.com/somlioy/amina_s/commit/65f9e46ebc438e6618e4185f81b845eb52af1130)

**Comment by somlioy** [comment]
A fix is beeing worked on regarding custom clusters such as 65255 from Amina; https://github.com/Koenkk/zigbee2mqtt/issues/22075#issuecomment-2059797422

**Comment by somlioy** [comment]
Zigbee2mqtt now supports custom clusters defined in device files.
I'm currently working a new version of the converter which supports this.

**Comment by magne74** [comment]
Perfect!

**Comment by somlioy** [comment]
@magne74 @EskildPa 
New version released with support of custom cluster 0xFEE7.
Please report back.
Works on my installation of Z2M version 1.37.1 ...

**Comment by somlioy** [comment]
@magne74 @EskildPa 
New version released with support of custom cluster 0xFEE7.
Works on my installation of Z2M version 1.37.1.

PR #4  

Closing this

**Comment by magne74** [comment]
@somlioy 
Ev status is now working:-) Thank you for very fast respond.

Only error message now is: Failed to apply calibration to 'current': 'current_precision' is not a number, got string () Shall I make a new issue for this?

**Comment by somlioy** [comment]
@magne74 Those are automatically created by Z2M and not specifially by this external converter. Try to remove the line with `current_precision: ''` under devices in your configuration.yaml file and then restart Z2M to see if that fixes the issue.

Related issue: https://github.com/Koenkk/zigbee2mqtt/issues/18169#issuecomment-1906289774

**Comment by magne74** [comment]
@somlioy That did the trick😊 Thanks!
