### ISSUE TITLE
Converter not reporting correctly after updating firmware to 1.8.7

### ISSUE THREAD

**Issue by magne74** [somlioy/amina_s#10]
After updating the firmware the device is not acting 100% any more in z2m.

**Comment by magne74** [comment]
Edit: I had to re-select attributes in the bind-window. Now everything is ok. Except from the reported firmware version. It still lists 1.5.3, but installed firmware is 1.8.7.

And: I have asked for updated zigbee-information to be published. Its on its way...

**Comment by somlioy** [comment]
Amina support previously mentioned that one might need to reset the charger after an update in order for it to "forget" its previous config...

> 1. Set rotary dip switch to 0
> 2. Turn Power off then on
> 3. Set rotary dip switch to desired level
> 4. Turn Power off then on again
> 5. The LED will blink continuously untill reset is finished

**Comment by magne74** [comment]
I did that😊

**Comment by bmork** [comment]
Same experience here.  I d.dn't bother doing the reset  when upgrading to 1.5.3, and assumed that was the reason I kept seeing "1.4.10".  But after upgrading to 1.8.7 and doing the full reset procedure (and removing the device from z2m first), I'm still seeing "1.4.10".  Looks like this version number is stored somewhere persistent.  Doesn't matter much I guess.  Just a bit confusing.

I'm pretty sure the upgrades were OK both times.  I'm using the nRF Connect app to read back the image in slot 1, and that showed the new versions both times.  Besides, I did get the expected zigbee interface changes after the 1.5.3 upgrade.

Still curious what changed in 1.8.7.

**Comment by ThorAlex87** [comment]
Version number is stuck on 1.5.3 here too, but the firmware upgrade app reads the correct number.

**Comment by somlioy** [comment]
I noticed that my charger now reports 1.8.7 correctly... Not sure what I've done other than reset as per procedure and power cycling.
![image](https://github.com/user-attachments/assets/552fa8f6-23ff-4cfd-b9da-ebda000001ce)

**Comment by bmork** [comment]
> I noticed that my charger now reports 1.8.7 correctly...

Noticed this as well.  And the docs are finally updated for 1.8.7 too, I see

**Comment by somlioy** [comment]
Fw 1.8.50 released, reports correct version immediately without doing the reset stuff.
