### ISSUE TITLE
Charger randomly turns on

### ISSUE THREAD

**Issue by ArnstadFredrik** [somlioy/amina_s#11]
Not entirely shure where the problem comes from, but the charger occationally turns on. I have Zigbee2MQTT running in HomeAssistant. The charger is controlled by a EV Smart Charging integration, so the charger should most of the time be turned off, but occationally it is simply on, without reporting from where it has been switched on. The Log in HomeAssistant simply reports it being "Turned On", without the cause, no switch, or automation.

Anyone else have similar problems?

**Comment by somlioy** [comment]
Probably the same reason as mentioned in #7 ?

**Comment by ArnstadFredrik** [comment]
Seems like it.
