### ISSUE TITLE
How to turn on/off amina s

### ISSUE THREAD

**Issue by erviem99** [somlioy/amina_s#14]
I installed this extension in HAOS but no entities are created except the default one for the amina s device itself. Is there anything I'm missing here? I added the file amino_s.js.

**Comment by somlioy** [comment]
Does it say "Supported" on the about page for the amina device? If not, the amina_s.js file is not loaded correctly.

**Comment by erviem99** [comment]
I found it. I was missing the external_converters section in Zigbee2mqtt configuration.yaml file.
