### ISSUE TITLE
Can you get sensors for power consumption?

### ISSUE THREAD

**Issue by magicus** [somlioy/amina_s#16]
I apologize if this is a question and not a proper bug report.

I am planning on buying an Amina S, but integration with Z2M is essential to me. I do not only want to be able to turn the charger on and off, I also want to be able to have it report how much electricity the charger consumes. Ideally, I'd like to see both the current consumtion (in ampere or watt), and the total consumption over time (in kWh).

Can I do that with this Zigbee integration? This sentence in the README confuses me:

> As of now, the exposes total_active_energy and last_session_energy is not updated automatically as the attributes are not reportable.

Does this mean that it is not possible to see how much energy the car consumes? Or does it mean that I need to program Home Assistant to poll the data?

**Comment by somlioy** [comment]
Current, Power and Energy is all available. As for the total_active_energy and last_session_energy they need to be polled manually. They will be automatically updated (as in reportable) in a later version of their firmware.

For now, the best is to create your own energy sensor by using the power measurement which is automatically updated. You can do this with an integration/riemann-sum.

**Comment by magicus** [comment]
Thanks! That sounds good enough for me. I'll get one of those, then.
