### ISSUE TITLE
Question of how to use and configure this device in Z2M

### ISSUE THREAD

**Issue by VVVVVVVip** [somlioy/amina_s#17]
I am lacking some experience with zigbee devices and z2m, and I hope I can get some tips from some of the others few Amina users here :-)

My charger is connected to 3-phase, but when charging power is only reporting for 1-phase, like 2300W instead of 6900W when charging with 3x10Amps.
Is it by design and can I change this in Z2M -> Device Setting(Specific) -> Power Calibration?

Is it possible to manually poll the reports Total Active Energy and Last Session Energy?
I have tried to read the cluster in the z2m device Dev.console, but the answer is always zero.
Strange was during installation i did several tries with interviewing the device until it find right router devices, and in one inteview it suddenly reported a value i Watt for Total Active Energy that seemed reasonable after have been used for two charging sessions, but it was lost after a while. (and never changed before that)

**Comment by somlioy** [comment]
It was indeed a mistake that the power attribute is only 1-phase. I have merged a new version from the dev-branch where this is rectified with 3 new attributes (total of 4) for power; Total Active Power, Power Phase A, B and C. (The new version require Z2M v. >= 1.40.1)

As for Total Active Energy and Last session Energy, there is indeed something funny going on as it sometimes reports 0. I have noticed this aswell. As they are also not reportable thus require manual polling, the best is to do an integration of the Total Active Power attribute outside of Z2M. In home assistant you can do this with a integrator/riemann-sum.

**Comment by VVVVVVVip** [comment]
I did a FW upgrade last week from 1.5.3, and I noted that the firmware was updated same day with version 1.8.**50**
Do Amina publish any changelogs somewhere?

Either way, upgrade whent fine. 
Some kind of error during update process in android DeviceManager app that I didn't get what it was about.
Uploaded the new js-file and interviewed the device again from z2m and it now nicely reports 3-phase, I can set offline behavior and also manually refresh Total Consumtion in z2m UI.
In one week my set max charge amp has not been reset, neither settings for offline behavior. Hope it keep it next week to :-)

Does your charger also reports a little low values for amps and watts during charging? 
I haven't had time to compare exactly, but I am quite sure it reports ~10% lower than it actual uses when I did a quick compare to the readings from my Shelly 3EM meter (using it for the whole house).

Also, if I remember correctly, before my charger was installed I did connect it briefly thru ZHA. Not very useful of course but I did get the power meters and a switch entities.
When setting the switch to off, the white led on the charger also went off, but since I converted to Z2M the led doesn't following the on/off switch.
Is it supposed to? 
Does the switch work at all?

**Comment by somlioy** [comment]
They publish change logs [here](https://doc.clickup.com/9004130215/p/h/8cb07x7-18308/c750786359b035a), however not updated for 1.8.50 yet ... Support said this update should fix the charger remembering the settings on power cycle, as I mentioned [here](https://github.com/somlioy/amina_s/issues/7#issuecomment-2358501644)

I also tried updating to 1.8.50 and the update went fine. Z2M reports correct SW version aswell. Still no success binding to total active energy 😒

Just checked the amp/current reports with my Fluke clamp meter at various current limits:
| Limit  | Z2M | Fluke |
| ------ | ---- | ----- |
| 6A  | 5.95A  | 6.1A |
| 7A  | 6.49A | 6.6A |
| 8A  | 7.11A | 7.2A |
| 9A  | 8.22A | 8.4A |
| 10A  | 8.97A | 9.6A |
| 11A  | 9.98A | 10.2A |
| 12A  | 11.15A | 11.4A |
| 13A  | 12.4A | 12.6A |
| 14A  | 13A | 13.2A |
| 15A  | 14.2A | 14.3A |
| 16A  | 15.4A | 15.6A |
| 17A  | 15.8A | 16.1A |

The Z2M values and the measured values with the Fluke meter is pretty much identical, however I notice that the current limit setting is a bit off ... 🤔

I just tested the on/off-switch and it definitely works. Charger doesnt turn off but disables charging (the light changes from blue (charging) to green (car connected but not charging).

Here are the light explanations from the Amina manual:
![image](https://github.com/user-attachments/assets/59a7c84e-0f23-4e77-8fca-c95b4f8c478b)

**Comment by VVVVVVVip** [comment]
Thanks!

I think I need to try my on/off switch a bit more...
And power metering. I think I actually consumes the set amps, but reports slightly less. Something to do a rainy day :-)
