### ISSUE TITLE
ev_status is not automatically updated

### ISSUE THREAD

**Issue by magicus** [somlioy/amina_s#19]
The ev_status attribute is not automatically updated in HA. When I click the "reload" button in the Z2M UI, it is immediately updated and this is propagated to HA. But if I don't, it seem to be stuck on the old value.

**Comment by somlioy** [comment]
Check that you’re bound to the clusters
![image](https://github.com/user-attachments/assets/b3713967-3fd8-4d66-9177-dce3cc3de800)

**Comment by magicus** [comment]
Only `haElectricalMeasurement` had a check box; I've checked the others from your screenshot and press the "Bind" button. I can't see any direct effect of this, though, so I just hope it did something. :-)

I double-checked the README, and I could not find anything about this. Is this required to do to get this device to work with Z2M? If so, maybe it should be documented.

Or is it possible to change the js file to do this automatically? Since `haElectricalMeasurement` was bound by default, maybe it is possible to have the other clusters bound as well? (I also realize I need to read up a bit on Zigbee, to understand this cluster and binding thing...)

**Comment by magicus** [comment]
I have now verified that this did indeed solve the problem. 

However, this should be documented or the js file updated to do so automatically. My understanding from browsing some other herdsman files indicate that there seem to be some kind of support for doing that.

**Comment by somlioy** [comment]
I have updated the converter with bindings among other things [88dcd55](https://github.com/somlioy/amina_s/commit/88dcd55b85f2926006229e0c034eb7053c5f5053), (#20)

**Comment by magicus** [comment]
Thanks! ❤️
