### ISSUE TITLE
Error "e is not defined" and other issues

### ISSUE THREAD

**Issue by ThorAlex87** [somlioy/amina_s#2]
Hi! Just had my charger installed and I'm trying to get this to work. Had to do the fix in #1, but after that I got a different error:

`Zigbee2MQTT:error 2024-04-17 15:08:04: Failed to load external converter file 'amina_s.js' (e is not defined)`

I then re-uploaded the file and did the fix again to make sure I'd not accidentally messed something up, and now it still won't work but there is nothing in the logs either.

Any ideas as to what's wrong, or what I can do to figure it out?

Thanks in advance!
Thor

**Comment by somlioy** [comment]
I just verified the converter in the dev branch (https://github.com/somlioy/amina_s/blob/dev/amina_s.js), which seems to work except for the issues regarding configuration mentioned in #1.

Check the latest log-files in the log folder.

**Comment by ThorAlex87** [comment]
Found this in the logs:

```
debug 2024-04-17 16:14:50: Passive device 'Amina S' was last seen '3.02' hours ago.
info  2024-04-17 16:14:50: MQTT publish: topic 'zigbee2mqtt/Amina S/availability', payload '{"state":"online"}'

info  2024-04-17 16:14:49: Amina S (0xf4ce364f12a7775a): Not supported (Unknown)
```

**Comment by somlioy** [comment]
That is just a regular fault if no external converter is found for the device. Did you register the .js file correctly in the configuration?
Also check the very beginning of the log file after a Z2M restart.

**Comment by ThorAlex87** [comment]
As far as I can tell it should be regisered correctly:
![Untitled](https://github.com/somlioy/amina_s/assets/111507745/e8c721d8-3ad0-479c-bf2b-0204df48aea0)
![Untitled2](https://github.com/somlioy/amina_s/assets/111507745/a6c19f70-2d99-4a51-95d7-9c967a8ac90d)

The error quoted in the first post is what I got on restart after fixing the file the first time. After redoing it I get no related errors on restart.

I did notice something weird thought:
`debug 2024-04-18 10:34:14: Received MQTT message on 'zigbee2mqtt/Billader Amina S/availability' with data '{"state":"offline"}'
debug 2024-04-18 10:34:14: Received MQTT message on 'zigbee2mqtt/Amina S/availability' with data '{"state":"online"}'`

The first line has the name i gave it the very first time I tried adding it, before upgrading the firmware. At the time it went offline for no reason after a short while, and Amina support helped me get it upgraded to the current firmware. Could that be related? There is no other reference to the old name in the logs.

Edit: Just realized I tried a quick reset of the charger last night, and did not rename it after adding it back in z2m. So when the above log file was created the device did not have any of those two names. These are all the lines in the log file related to the current name:

```
info  2024-04-18 10:34:10: 0xf4ce364f12a7775a (0xf4ce364f12a7775a): Not supported (Router)

debug 2024-04-18 10:34:11: Active device '0xf4ce364f12a7775a' was last seen '4.98' minutes ago.
info  2024-04-18 10:34:11: MQTT publish: topic 'zigbee2mqtt/0xf4ce364f12a7775a/availability', payload '{"state":"online"}'

debug 2024-04-18 10:34:14: Active device '0xf4ce364f12a7775a' was last seen '4.99' minutes ago.
```

**Comment by somlioy** [comment]
What firmware is the charger currently running?

**Comment by ThorAlex87** [comment]
1.5.3, the version Amina sent me on Tuesday so it should be the newest.

**Comment by somlioy** [comment]
Strange, my Amina is running the same FW and I'm not having the same issues as you.
Did you download the file from the dev branch or did you just copy the code?

Could it be that you removed the "const exposes" line instead of the "const extend" line?

**Comment by ThorAlex87** [comment]
> Strange, my Amina is running the same FW and I'm not having the same issues as you. Did you download the file from the dev branch or did you just copy the code?

I downloaded the file.

> Could it be that you removed the "const exposes" line instead of the "const extend" line?

Just checked, looks correct.


The charger is currently marked as offline, not sure if that is normal behaviour for unsupported devices or if it's dropped the connection? I did restart it with no change.

**Comment by somlioy** [comment]
@ThorAlex87 New version released with support of custom cluster in the newest Z2M version (1.37.1). Please try this to see if this solves your problem.

**Comment by ThorAlex87** [comment]
Success! Had to reset the charger again after adding the new file, but now it works!

Thank you so much!
