### ISSUE TITLE
Amina S Control (0xFEE7) not defined

### ISSUE THREAD

**Issue by magne74** [somlioy/amina_s#3]
I get this message:
Failed to configure 'Laderen', attempt 1 (Error: Cluster with name '65255' does not exist at getClusterDefinition (/app/node_modules/zigbee-herdsman/src/zcl/utils.ts:72:19) at Object.getCluster (/app/node_modules/zigbee-herdsman/src/zcl/utils.ts:177:29) at Function.create (/app/node_modules/zigbee-herdsman/src/zcl/zclFrame.ts:46:31) at Endpoint.zclCommand (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:755:36) at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:401:40) at Object.configure (/app/data/extension/externally-loaded.js:185:28) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Configure.configure (/app/lib/extension/configure.ts:121:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:21) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

Can it be fixed?

**Comment by somlioy** [comment]
Yes, working on a fix for support to Z2M 1.37.1

**Comment by somlioy** [comment]
Also see issue #1.
Closing this.
