### ISSUE TITLE
will you push this upstream?

### ISSUE THREAD

**Issue by bmork** [somlioy/amina_s#5]
Looks more than good enough to me.  Having it upstream will increase the test coverage and prevent anyone from doing unnecessary double work. 

Thanks for creating this.  Works for me as far as I am able to test. Still missing a car to charge :-)

**Comment by AlfHou** [comment]
+1 would be nice to have this upstream

**Comment by magicus** [comment]
I have just installed my Amina S box, and am very grateful for the work you have done here!

@somlioy Would you appreciate assitance in getting this pushed upstream into herdsman?

**Comment by somlioy** [comment]
I have a created a pull-request upstream which will hopefully be merged soon.

**Comment by somlioy** [comment]
Amina S is now supported in Z2M as of version [1.41.0](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.41.0) [(ZHC PR #8191)](https://github.com/Koenkk/zigbee-herdsman-converters/pull/8191)
