### ISSUE TITLE
Can't install - "external converters must be array"

### ISSUE THREAD

**Issue by VVVVVVVip** [somlioy/amina_s#9]
I have just succeed to get Z2M up and running (HA addon)
The sole purpose of switching to Z2M was to be able to use the Amina S that is unsupported in ZHA, and I found this External Converter that gave me some hope.

But when I try to add the External Converter in Z2M i get an error message **"external converters must be array"** that I don't understand, and I didn't find anything useful when googling.

I uploaded the files amina_s.js and amina_s.png into my zigbee2mqtt folder, using the File Editor addon.
Next, in Z2M under external converters, I click the +button, write amina_s.js and click Submit, then the error message passes by.

![bild](https://github.com/somlioy/amina_s/assets/92485071/85aba616-55bd-4b02-839b-a8204dbae4e0)

**Comment by somlioy** [comment]
I've not encountered that issue before. What coordinator are you using?

**Comment by VVVVVVVip** [comment]
I am using a SMLIGHT SLZB-06p7
Lan connection

**Comment by somlioy** [comment]
Make sure that `amina_s.js` is in the data-folder and not in the root directory of Z2M.

**Comment by VVVVVVVip** [comment]
> Make sure that `amina_s.js` is in the data-folder and not in the root directory of Z2M.

There is no more folders (except log) under z2m.
I put your file in same folder as configuration.yaml as described in installation instructions.
Attached a screenshot. 
![Screenshot_20240618_094743_Home Assistant](https://github.com/somlioy/amina_s/assets/92485071/edec0630-7c3f-4e6d-a802-6f5e3012b44d)

**Comment by VVVVVVVip** [comment]
Another thought.
I haven't included my Amina in my network yet, because I assume the convert should be installed first. But maybe I am wrong?

**Comment by somlioy** [comment]
Not sure about that...
You should however be able to pair the device without the converter installed. It should then be marked as "unsupported", but some attributes should be visible.

**Comment by VVVVVVVip** [comment]
Another thought.
I haven't included my Amina in my network yet, because I assume the convert should be installed first. But maybe I am wrong? 

> Not sure about that... You should however be able to pair the device without the converter installed. It should then be marked as "unsupported", but some attributes should be visible.

Probably right. I used ZHA earlier and it only identified on/off switch and some energy sensors.

But do you think it is something wrong with my z2m installation since I don't have the data folder you mentioned?

I asked about the array error in HA Discord channel and they said it is something wrong in the converter, so that's why I am here 😊

**Comment by somlioy** [comment]
Wether you have the data folder or not is probably dependent on type of z2m installation. I believe it is correct as long as it is in the same folder as the config.yaml file.

What Z2M version are you running?
Also show this part of your configuration.yaml file:
![image](https://github.com/somlioy/amina_s/assets/28142915/d62cfc2b-3589-421e-ae4a-71cf92f7dd01)

If that part is at the end of your file, try to add a blank line

**Comment by VVVVVVVip** [comment]
Current version of z2m is 1.38.0-1

First I didn't have write anything in config, then I found an example in Z2M instructions and added this
![Screenshot_20240618_140231_Home Assistant](https://github.com/somlioy/amina_s/assets/92485071/cc245dad-eb1c-4ca4-bc7f-ce73b69ecee5)
But same array error appeared, so I removed the two lines again.

Just tried to add them again, and restart HA.
When z2m started up I noticed another error, that mention converters
![Screenshot_20240618_140713_Home Assistant](https://github.com/somlioy/amina_s/assets/92485071/2d78cb13-2739-4942-a2c0-603134d1c73d)
Could this be related?

Still array error when trying to submit js file.

**Comment by VVVVVVVip** [comment]
> Wether you have the data folder or not is probably dependent on type of z2m installation. I believe it is correct as long as it is in the same folder as the config.yaml file.
> 
> What Z2M version are you running? Also show this part of your configuration.yaml file: ![image](https://private-user-images.githubusercontent.com/28142915/340664363-d62cfc2b-3589-421e-ae4a-71cf92f7dd01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNDQ4MTgsIm5iZiI6MTcxOTE0NDUxOCwicGF0aCI6Ii8yODE0MjkxNS8zNDA2NjQzNjMtZDYyY2ZjMmItMzU4OS00MjFlLWFlNGEtNzFjZjkyZjdkZDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDEyMDgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhYTVjYTEwZWMzMGRhYTFkYWIxZTI1MDRjNGQwYzk0MGY5MWMzNjU3MDg1YWQ4NjEzYjMzYzA1MDc2MDc1YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1vIyl6xWpfYkfgU2CaRNdf-aQVTZZGt5A4USlblTL3Y)
> 
> If that part is at the end of your file, try to add a blank line

Hi again. 
I noticed that it stood that you have tested this on Z2M 1.37.1. Have you tried it in 1.38.1 also?

**Comment by somlioy** [comment]
I can't see that 1.38.1 is released? I just tried 1.38.0 and the converter loads correctly.

**Comment by VVVVVVVip** [comment]
> I can't see that 1.38.1 is released? I just tried 1.38.0 and the converter loads correctly.

You are right, I misread the version number.

I tried to read about what z2m can mean by array, but this is sadly far away of my area of knowledge.

I found it mentioned here:
_**Ensure that default export from your external converter exports an array or device object (refer to the definition in the devices folder of zigbee-herdsman-converters).**_
[https://www.zigbee2mqtt.io/guide/configuration/more-config-options.html#network-map](url)

And two mentions here, [https://www.zigbee2mqtt.io/guide/usage/exposes.html#generic](url)
**_The specific and the generic composite type will always have a features property, this is an array containing the generic exposes types. Optionally both types can have a property endpoint, indicating the device exposes this capability on a specific endpoint._**
![image](https://github.com/somlioy/amina_s/assets/92485071/25ac4ab9-2b4e-494b-a25a-1a608a2e6156)

But if any of this relates to your converter I just don't understand.

**Comment by VVVVVVVip** [comment]
Problem solved!
Got some help in Z2M Discord channel.

They think it is something wrong in Z2M UI.

But the documentation for install an external converter is also wrong.
It should be installed in UI (when it is fixed) **OR** in configuration.yaml - Not both.

So with this new knowledge my charger is included and seems to work. (it is not installed in final location yet)

The only thing missing is the Amina icon, do I need to do something more with the png than upload to same folder as config/js file?

**Comment by somlioy** [comment]
Great to hear. Closing the issue then.

As for the icon, this is not implemented in the converter as the image must manually be placed in the Z2M-frontend.
I just tried what is described in this comment with success:
https://github.com/Koenkk/zigbee2mqtt/discussions/15591#discussioncomment-4475790
![image](https://github.com/somlioy/amina_s/assets/28142915/72d8230c-c1f0-459f-aacb-048d6005dadd)
